cfengine/build-index

index.json

CFE-3750: Update modules to get python 3.5 compatability

---

index.json

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

Update commit sha's

---

index.json

Ticket: CFE-3782
Changelog: Title

CFE-3782: Added module for inventorying user logins

---

index.json

Ticket: ENT-7672
Changelog: Title

ENT-7672: Added module that inventories systemd service units that are running

---

cfbs.json

Originally committed to the wrong file: https://github.com/cfengine/build-index/pull/50

Bumped lib-fim to 0.1.1

---

cfbs.json

Ticket: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

Changed the name of groups_experimental to groups

---

scripts/s3uploading.js

Fixed readme finding process ignoring subdirectory

---

versions.json

fixed readmes for subdirectories

Re-uploaded readmes

---

cfbs.json

~Requires https://github.com/cfengine/modules/pull/40 to be merged first and the `commit` here should be changed to the merge-commit, I think.~

Add the http promise module

---

scripts/s3uploading.js
versions.json

Added `steps`, `subdirectory`, `by` and `repo` properties to versions.json

---

cfbs.json

Update lynis version to cleanup README

---

cfbs.json

And use the same commit from the repo for the
telnet-server-not-installed module too.

Add the openldap-server-not-installed module

---

cfbs.json

Reverts cfengine/build-index#192

Revert "Added ftp-server-not-installed and all-packages-upgraded modules"

---

cfbs.json

Signed-off-by: larsewi <lars.erik.wik@northern.tech>

Expanded readme

---

.github/workflows/mirroring.yml
.gitignore

Ticket: CFE-3868
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

CFE-3868: GHA for versions.json no longer fails when no changes are needed

---

.github/workflows/compare_index_changes.py

When ever an URL is introduced or changed, a head request is made in
order to check that the resource is reachable.
Another PR to cfbs will remove HEAD requests from the validate command: https://github.com/cfengine/cfbs/pull/96
Ticket: CFE-3904
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

GH Action: Validate remote resources in index

---

cfbs.json

"experimental" for modules which are not ready for wide-spread use
"supported" for modules which are ready for (production) use
"tmp" for modules relating to /tmp
"sudo" for modules relating to the sudo tool
"inventory" for modules which add inventory (reporting) data
"security" for security related modules
etc...

Updated tags for several modules

---

CONTRIBUTING.md
cfbs.json

Ticket: CFE-3905
Changelog: none
requires https://github.com/cfengine/cfbs/pull/112 to be merged and released before CI here will pass due to validate function changing.

Modules can now have -1 -2 versions

---

cfbs.json

Now that cfbs has - support in versions, we are moving to align versions with
things people will recognize.

Added proper version for masterfiles module

---

cfbs.json

https://github.com/nickanderson/cfengine-lynis/compare/029a34701c165b4a43e30da7088548e26658516e..c63c5366f4948f29481c7d35cd65ae67a7a00cd3

Bumped lynis to 3.0.1

---

cfbs.json

Depends on https://github.com/cfengine/build-index/pull/262

Added lynis-compliance-report v0.0.1

---

cfbs.json

This module inventories local groups and optionally each groups users.

Added inventory-local-groups v0.0.1

---

.github/workflows/compare_index_changes.py
cfbs.json

ENT-9366: Rename ftp-server-not-installed and all-packages-upgraded modules

---

cfbs.json

Merge together: https://github.com/cfengine/modules/pull/47

Bumped promise-type-http to v1.1.0

---

cfbs.json

First to publish a module with inputs!

CFE-4073: Added file-permissions module

---

cfbs.json

ENT-9455: Added delete-files/v0.0.1

---

cfbs.json

ENT-9660: Add enable-aslr module

---

cfbs.json
versions.json

- Added punctuation to the end of descriptions
- Improved the descriptions of many modules
- Removed unnecessary trailing slash in subdirectory fields
- versions.json: Removed unnecessary trailing slashes in subdirectories
- Improved the description of more modules

Made descriptions and subdirectories more consistent

---

cfbs.json

- Added uninstall-apache module
- Added uninstall-dhcp module
- Added uninstall-bind module
- Added uninstall-dovecot module
- Added uninstall-samba module
- Added uninstall-squid module
- Added uninstall-xinetd module
- Updated enable-aslr to 1.0.0
- Updated uninstall-rsh-server to 1.0.0
- Updated uninstall-talk to 1.0.0

Added 7 modules and updated others

---

cfbs.json

CFE-4167: Fixed path to etc-issue-content build input

---

cfbs.json

Bumped inventory-fips-mode-setup to 0.1.2

---

cfbs.json

See:
https://github.com/cfengine/masterfiles/commit/4bd0f0bb16ce2c0dcb4ccbddf33fdf2b96e7a2d1

Added masterfiles 3.21.1-2

---

cfbs.json

- Added packages-allowlist-snapshot version 0.0.2
- Removed 'This module' from module description

Added packages-allowlist-snapshot version 0.0.2

---

cfbs.json

See: https://github.com/cfengine/modules/pull/82

conditional-installer: Fixed input spec

---

cfbs.json

Merge together:
- https://github.com/cfengine/modules/pull/84

Added autorun-bundles and autorun-inputs modules

---

cfbs.json

- PR updating modules: https://github.com/nickanderson/cfengine-lynis/pull/10

Updated lynis to 3.0.9

---

cfbs.json

For this change: https://github.com/nickanderson/cfengine-inventory-sudoers/pull/4

inventory-sudoers v1.0.3

---

cfbs.json

https://cisofy.com/downloads/lynis/
https://github.com/nickanderson/cfengine-lynis/compare/b6fb66e7ddb81c722f0ede500094ab30702bf0bf..70bdf7be29c890d3bf162a8fe993e8d12eb61388

Upgraded Lynis to 3.1.1

---

scripts/s3uploading.js
versions.json

Ticket: ENT-11783
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>

ENT-11783: dependencies listed in the versions.json file

---

cfbs.json

Expanded compliance report checks to cover all Lynis checks
With the speedups in Mission Portal we can have much bigger compliance reports
while maintaining usability.
Seeing ~5x speed up in testing.

compliance-report-lynis/v3.1.1-2

---

.github/workflows/mirroring.yml

https://github.com/cfengine/create-pull-request/releases/tag/v7

create-pull-request: Upgraded to v7

---

cfbs.json

Added package-method-winget module and its dependency powershell-execution-policy

---

cfbs.json

- **Revert "upgrade promise-type-git to 0.0.2"**
- **Upgrade promise-type-git from 0.2.5 to 0.2.6**

promise type git 0.2.6

---

cfbs.json

- Added masterfiles 3.21.6 version

Release 3.21.6 masterfiles

---

cfbs.json

Added inventory-windows-services module to index

---

cfbs.json

This reverts commit 619c242db297fb3131fa2fe2ae0428408ff91190.

Set default masterfiles back to 3.24.1

---

.github/workflows/mirroring.yml

Changed contents permission to write as create-pull-request requires it

Fixed mirroring action permission

---

cfbs.json

- **cfbs.json: Removed unnecessary name fields in index**
- **cfbs.json: Standardized tags a bit**

Small cleanups
