index.json

- Updated name and description to be more accurate for what the policy provides.
- Updated cfbs steps to avoid running a shell command and instead use native integration steps for copying and merging json.

Renamed local-users to inventory-local-users

---

index.json

Merge together:
https://github.com/cfengine/masterfiles/pull/2107
Before:
```
❯ ls -a out/masterfiles
.               templates            configure         MPF.md
..              tests                configure.ac      promises.cf
autom4te.cache  travis-scripts       CONTRIBUTING.md   promises.cf.in
cfe_internal    aclocal.m4           example_def.json  README.md
controls        .CFVERSION           .gitignore        standalone_self_upgrade.cf
.git            CFVERSION            install-sh        standalone_self_upgrade.cf.in
inventory       CHANGELOG.md         LICENSE           test-driver
lib             CODE_OF_CONDUCT.org  .mailmap          .travis.yml
m4              config.guess         Makefile          update.cf
misc            config.log           Makefile.am
modules …
```

CFE-3781: Deleted extra cruft from the masterfiles build

---

index.json

It's not seen any maintenance for some time.
Ticket: ENT-7671
Changelog: Title

ENT-7671: Removed cis framework from index

---

index.json

Checks a list of candidates for sudo access, by default the list of candidates
includes users found in /etc/passwd. To inventory a different list, either
define a list of candidates or define the variable that candidates should be found in.

ENT-7683: Added inventory-sudoers

---

cfbs.json

None of these modules with the supported tag will create a dynamic number of inventory attributes.

Set supported tag on some modules

---

.github/workflows/all-modules-add-and-buildable.yaml

The workflow files for that commit SHA and Git ref are inspected, and a new workflow run is triggered for any workflows that have on: values that match the triggering event.
The workflow runs on your repository's code at the same commit SHA and Git ref that triggered the event. When a workflow runs, GitHub sets the GITHUB_SHA (commit SHA) and GITHUB_REF (Git ref) environment variables in the runner environment. For more information, see "Using environment variables."
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule

Fixed github action schedule syntax

---

cfbs.json

Reverts cfengine/build-index#124

Revert "Bumped masterfiles to v3.18.1"

---

.github/workflows/compare_index_changes.py

Fixed issue where updating commit but not version was not detected by the `compare_index_changes` was not detected as an error.

Fixed `compare_index_changes` workflow issue

---

cfbs.json

[issue](https://github.com/larsewi/cfengine-prelinking-disabled/issues/2)
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

Fixed missing check for prelink being available on the system

---

cfbs.json

To make sure /tmp is mounted with the 'nosuid' option.
Ticket: ENT-8225

Add the tmp-nosuid module

---

cfbs.json

A new version that also manages fstab or the /tmp mount unit.

Update the tmp-nosuid module to version 0.0.2

---

cfbs.json

Since cfengine/masterfiles@f3a8f65e77428 there's a new script
that converts a directory with freshly cloned MPF into a
ready-to-use masterfiles directory.
Ticket: CFE-3872

Update the masterfiles module to new version with prepare.sh

---

cfbs.json

Several improvements here:
- Avoid ugly inform log about not being able to hash file before it's downloaded
- Fall back to wget if curl is not available
- Default version of lynis now 3.0.7 (current latest)
- Moved lynis scan info output to verbose mode

Bumped lynis module version to 0.2.0

---

cfbs.json

This version handles pool entries in addition to the existing handling of server entries for ntp.conf
https://github.com/nickanderson/cfengine-security-hardening/pull/16

Bumped ntp-maxpoll to v0.0.3

---

cfbs.json

This version fixes the source path to copy from when installing compliance
reports. Now the source is masterdir, not inputs.
Ticket: ENT-8849

ENT-8849: Bumped compliance-report-imports to version 0.0.6

---

cfbs.json

Note, this is presumptive. Release tags have not been made at the time of this writing. Please double check.

ENT-8952: Released masterfiles 3.20.0

---

cfbs.json

https://github.com/nickanderson/cfengine-security-hardening/compare/6f6996bc36c07c91bcf9da9276d434cc0426ee97..14fafaf0a4e118830f26e062827979fcc6be5cf4

Bumped compliance-report-imports to version 0.0.7

---

cfbs.json

- Default version of Lynis bumped to 3.0.8
- Variables used to configured desired version of Lynis have changed, no longer looking for variables in `default:def`.
- New Inventory attributes
- CISOfy Lynis date scan completed
- CISOfy Lynis days since scan completed
https://github.com/nickanderson/cfengine-lynis/compare/f1bf2c0c9f6ccca54085f05e914351aad8e52852..029a34701c165b4a43e30da7088548e26658516e

Bumped lynis to 0.3.0

---

cfbs.json

This module parses /etc/group into variables that can be re-used.

Added library-parsed-local-groups v0.0.1

---

cfbs.json

This has a change to the importer to pass --form 'source=build moudle' in the
curl command which is used to set the appropriate system owner.

ENT-8260: Bumped compliance report importer to 0.0.8

---

cfbs.json

Renamed 'prelinking-disabled' to 'disable-prelinking' in order to conform with the new recomendations.
Ticket: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

Rename module according to recomendations

---

cfbs.json

- Renamed telnet-server-not-installed to uninstall-telnet-server
- Renamed openldap-server-not-installed to uninstall-openldap-server
See:
https://github.com/vpodzime/cfengine-security-hardening/pull/5
https://tracker.mender.io/browse/ENT-9366

Renamed openldap-server and telnet-server modules

---

cfbs.json

with support for setting classes.
See PRs https://github.com/cfengine/modules/pull/62 and https://github.com/cfengine/masterfiles/pull/2547 for details.

Update library-for-promise-types-in-bash to 0.1.2

---

cfbs.json

```
$ cfbs --force --non-interactive init
$ cfbs --non-interactive remove masterfiles
$ cfbs --non-interactive add https://github.com/cfengine/masterfiles@0de3ef61988670dbf0afa8b29fe4d269ead4c655 masterfiles
$ cfbs --non-interactive add https://github.com/cfengine/modules inventory-local-users-unhashed-password
$ cfbs status
Name:        Example project
Description: Example description
File:        cfbs.json
Modules:
001 masterfiles                             @ 0de3ef61988670dbf0afa8b29fe4d269ead4c655 (Downloaded)
002 library-parsed-local-users              @ ede282c34083ab807543aa734b1142228ab98993 (Downloaded)
003 inventory-local-users-unhashed-password @ 057f24c8e96ef5504779d45f3f8a19907ccf0b32 (Downloaded)
```
See example in module readme for setting up a couple of users that will …

Added inventory-local-users-unhashed-password version 1.0.0

---

cfbs.json

- Updated supported operating systems
- Fixed description of Supported Debian (removed Debian 9)
- Fixed description of Supported Ubuntu (added Ubuntu 22)
- Removed RHEL 7
- Added RHEL 9
- Removed CentOS 7
- Removed Windows 2016
- Added Windows 11, 2022
- Adjusted OS is reported to not consider Unknown OS as reported
https://github.com/nickanderson/cfengine-security-hardening/compare/1b9d2fab3d3fd43fae3d34f864c8cfa4574b01b4..d828be6de5b73b0058e4367c2ab09bda1cf035ca
Ticket: ENT-9736
Changelog: Title

ENT-9736: Updated compliance-report-os-is-vendor-supported to version 0.0.4

---

cfbs.json

Silenced output for ease-of-use. Bumped version from 0.0.2 to 1.0.0, it has been working well for me on various platforms.

Upgrade upgrade-all-packages module

---

cfbs.json

This version uses a different URL for the image in the README so that it will
work more nicely on build.cfengine.com.

Bumped inventory-ssh-host-key-fingerprints to v0.0.2

---

cfbs.json

Masterfiles did not change between 3.21.0 and 3.21.1, so the commit is the same,
but the versioned artifacts differ in the actual version strings.

ENT-10032: Added masterfiles 3.21.1

---

.github/workflows/mirroring.yml

Some modules, notably masterfiles, rely on git to determine version numbers.

Ensure we fetch tags before building a module

---

cfbs.json

Reverts cfengine/build-index#435

Set default masterfiles back to 3.21.2

---

versions.json

This changes sets EXPLICIT_VERSION so that we do not end up with commit shas as
part of the version strings in the built policy.
For example, we get "CFEngine Standalone Self Upgrade 3.22.0" instead of
"CFEngine Standalone Self Upgrade 3.22.0a.2708fa941".
Ticket: ENT-10331

ENT-10331: Fixed policy version for 3.22.0

---

cfbs.json

This was already fixed for all the different versions in versions.json, but the new build steps were not carried over to the index, where the default one is listed.
We can improve this in other ways: add a warning to cfbs, and add CI to check consistency between the two files.

Fixed masterfiles 3.21.2 so it doesn't have commit SHA in version

---

cfbs.json

See that the policy looks for the `packages` key, not the `name` key.
https://github.com/cfengine/modules/blob/26e0151745b342dbd8b5206c17c3e075622cec77/security/conditional-installer/main.cf#L27

ENT-10745: conditional-installer: Fixed input key name

---

cfbs.json

For this change: https://github.com/nickanderson/cfengine-security-hardening/pull/29

ENT-11146: Bumped compliance-report-imports to 0.0.9

---

cfbs.json

The related change: https://github.com/nickanderson/cfengine-security-hardening/commit/1afe01806fb18e764f904eda6e3cc49f9c9ff3dd

ENT-11210: Bumped compliance-report-imports to 0.0.10

---

cfbs.json

Mostly just to align the meta vs metadata parameter name, and cleaned up their READMEs.
- **Upgraded library-for-promise-types-in-python to version 0.2.2**
- **Upgraded promise-type-ansible to version 0.2.2**
- **Upgraded promise-type-git to version 0.2.3**
- **Upgraded promise-type-groups to version 0.2.4**
- **Upgraded promise-type-http to version 2.0.1**
- **Upgraded promise-type-systemd to version 0.2.3**

Patch releases for the promise type modules from cfengine/modules

---

cfbs.json

This version change introduces module input. The module input defaults match the
policy defaults so the behavior remains the same if module input is provided or
not.
This version does change a couple variables to be overridable via Augments:
- lynis:globals.hash_type
- lynis:global.tar_url

Bumped Lynis module version from 3.1.1 to 3.1.1-2

---

cfbs.json

Small change: removed purge policies class that is no longer needed after 3.18.x is end of life.

bump demo module version from 1.0.0 to 1.0.1

---

cfbs.json

Adds how to provide authentication via git credentials and added patch to set $HOME variable to enable that to work.
Change is here: https://github.com/cfengine/modules/pull/107

upgrade promise-type-git to 0.0.2

---

cfbs.json

ENT-12516: Bumped compliance-report-os-is-vendor-supported from 0.0.5 to 0.0.6

---

.github/workflows/mirroring.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replaced deprecated set-output with GITHUB_OUTPUT in the s3 mirroring action

---

cfbs.json

This reverts commit 44476a1d56bf5196e6609392aac6097acebe50d9.

Set default masterfiles back to latest LTS: 3.24.2

---

.github/workflows/mirroring.yml

reference - https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#example-of-a-multiline-string
Ticket: ENT-13092

Fixed multiline set of GITHUB_OUTPUT variable in the mirroring.yml

---

cfbs.json

Newer versions of cfbs have `replace` and `replace_version` build steps, allowing us to not hard code version numbers inside python files.

Module version fixes
